services:
  postgres:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: skillproof
      POSTGRES_PASSWORD: skillproof
      POSTGRES_DB: app_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "8090:5432"

volumes:
  postgres_data: